app_manager:
    type: rest
    prefix: /api
    resource: "@ManagerBundle/Resources/config/routes.yml"
    defaults: {_format: json}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

default_manager:
    resource: "@ManagerBundle/Controller/DefaultController.php"
    type:     annotation

default_doc:
    resource: "@DocBundle/Controller/DefaultController.php"
    type:     annotation